name: app
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  flutter_screenutil: 5.7.0
  melos:

  flutter_module:
    git:
      url: https://Thanh54833@bitbucket.org/concung/cci.mobile.fluttermodule.git
      ref: beta_new

dependency_overrides:

  package_info_plus: ^4.0.2
  permission_handler: 10.0.2
  ffi: ^1.1.2
  win32: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/.env
    - assets/env
  fonts:
    - family: ConCung
      fonts:
        - asset: fonts/ConCung.ttf
