name: app
description: A new Flutter project.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  flutter_screenutil: 5.9.0
  package_info_plus: 
  permission_handler: 10.3.0
  ffi:
  melos:

  package_management:
    git:
      url: https://bitbucket.org/concung/cci.mobile.flutter.packagemanagement.git
      ref: main

  flutter_module:
    path: ../flutter_module
  flutter_lints: ^3.0.1

dependency_overrides:
  provider: 5.0.0
  ffi: 1.1.2
  uuid: 3.0.7
  socket_io_client: 2.0.1
  omicall_flutter_plugin:
    git:
      url: https://github.com/VIHATTeam/OMICALL-Flutter-SDK.git
      ref: 3.0.13

  livetalk_sdk:
    git:
      url: https://github.com/VIHATTeam/OMICALL_CHAT_SDK.git
      ref: v0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/.env
    - assets/env
  fonts:
    - family: ConCung
      fonts:
        - asset: fonts/ConCung.ttf
