name: app
description: A new Flutter project.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  flutter_screenutil: 5.7.0
  melos:

  flutter_module:
    path: ../flutter_module

dependency_overrides:

  omicall_flutter_plugin:
    git:
      url: https://github.com/VIHATTeam/OMICALL-Flutter-SDK.git
      ref: 3.0.13

  livetalk_sdk:
    git:
      url: https://github.com/VIHATTeam/OMICALL_CHAT_SDK.git
      ref: v0.0.9

  package_management:
    git:
      url: https://Thanh54833@bitbucket.org/concung/cci.mobile.flutter.packagemanagement.git
      ref: 0.0.2

  package_info_plus: ^4.0.2
  permission_handler: 10.0.2
  ffi: ^1.1.2
  win32: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/.env
    - assets/env
  fonts:
    - family: ConCung
      fonts:
        - asset: fonts/ConCung.ttf
